import os
import sys
from pathlib import Path

from dotenv import load_dotenv

PROJECT_ROOT = Path(__file__).resolve().parents[2]
load_dotenv(PROJECT_ROOT / ".creds" / ".env", override=False)

# Use the running interpreter — works on Windows venv and Docker Linux
PYTHON_EXE = sys.executable

# JWT
JWT_SECRET_KEY = os.environ.get("JWT_SECRET_KEY", "CHANGE_ME_IN_PRODUCTION")
JWT_ALGORITHM = "HS256"
JWT_ACCESS_TOKEN_EXPIRE_MINUTES = 30
JWT_REFRESH_TOKEN_EXPIRE_DAYS = 7

# Fernet encryption for output files at rest.
# Generate with: python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
# Set ENCRYPTION_KEY env var. If absent, output files are stored plaintext (dev mode only).
ENCRYPTION_KEY: str | None = os.environ.get("ENCRYPTION_KEY")

# Default admin seeded on first startup
ADMIN_USERNAME = os.environ.get("ADMIN_USERNAME", "admin")
ADMIN_PASSWORD = os.environ.get("ADMIN_PASSWORD", "CHANGE_ME_IN_PRODUCTION")

# Rate limiting (applied globally via middleware)
RATE_LIMIT_DEFAULT = "10/minute"

# File upload constraints
MAX_UPLOAD_BYTES = 50 * 1024 * 1024  # 50 MB
ALLOWED_EXTENSIONS = {".xlsx", ".xls", ".csv"}

# Output file retention per module (keep N most recent)
OUTPUT_RETENTION_COUNT = 5

# SQLite DB path (bind-mount in Docker to persist across restarts)
DB_PATH = Path(os.environ.get("DB_PATH", str(PROJECT_ROOT / ".api_data.db")))

# TLS certificate paths (set via env or default; generated by start.sh if absent)
SSL_KEYFILE = os.environ.get("SSL_KEYFILE", str(PROJECT_ROOT / "certs" / "server.key"))
SSL_CERTFILE = os.environ.get("SSL_CERTFILE", str(PROJECT_ROOT / "certs" / "server.crt"))

# Root path used by SSC and XHI scripts (hardcoded in their source).
# On Docker/Linux set MEDICAL_DB_ROOT=/app; on Windows defaults to original path.
MEDICAL_DB_ROOT = os.environ.get("MEDICAL_DB_ROOT", r"D:\Work_Folder\medical_db")

MODULE_SCRIPT = {
    "mca": PROJECT_ROOT / "src" / "MCA" / "scripts" / "main.py",
    "hct": PROJECT_ROOT / "src" / "HCT" / "scripts" / "main.py",
    "ssc": PROJECT_ROOT / "src" / "SSC" / "scripts" / "main.py",
    "cam": PROJECT_ROOT / "src" / "CAM" / "scripts" / "main.py",
    "cim": PROJECT_ROOT / "src" / "CIM" / "scripts" / "main.py",
    "xhi": PROJECT_ROOT / "src" / "XHI" / "scripts" / "main.py",
}

MODULE_INPUT_DIR = {
    "mca": PROJECT_ROOT / "src" / "MCA",
    "hct": PROJECT_ROOT / "src" / "HCT",
    "ssc": PROJECT_ROOT / "src" / "SSC",
    "cam": PROJECT_ROOT / "src" / "CAM",
    "cim": PROJECT_ROOT / "src" / "CIM",
    "xhi": PROJECT_ROOT / "src" / "XHI",
}

MODULE_OUTPUT_DIR = {
    "mca": PROJECT_ROOT / "src" / "MCA" / "output",
    "hct": PROJECT_ROOT / "src" / "HCT" / "output",
    "ssc": PROJECT_ROOT / "src" / "SSC" / "output",
    "cam": PROJECT_ROOT / "src" / "CAM" / "output",
    "cim": PROJECT_ROOT / "src" / "CIM" / "output",
    "xhi": PROJECT_ROOT / "src" / "XHI" / "output",
}

OUTPUT_GLOB = {
    "mca": "MCA_consolidated_*.xlsx*",
    "hct": "HCT_Consolidated_*.xlsx*",
    "ssc": "SSC_consolidated_*.xlsx*",
    "cam": "CAM_consolidated_*.xlsx*",
    "cim": "CIM_consolidated_*.xlsx*",
    "xhi": "XHI_consolidated_*.xlsx*",
}

MODULE_EXTRA_ARGS = {
    "mca": [],
    "hct": ["--base-dir", str(PROJECT_ROOT / "src" / "HCT")],
    "ssc": [],
    "cam": [],
    "cim": [],
    "xhi": [],
}

# Input files to delete after a successful pipeline run (data files only, not templates)
MODULE_INPUT_FILES = {
    "mca": [
        "Patients by Insurance.xlsx",
        "Patients With Visits By Insurance.xlsx",
        "Patients by Diagnosis or Medication.xlsx",
        "patient-list.xlsx",
        "patient-list.xls",
        "Appointment Report.xlsx",
        "Copay Report.xlsx",
        "Services by Provider Summary.xlsx",
    ],
    "hct": [
        "patient-demographics.xlsx",
        "patient-insurance.xlsx",
        "HCT_Location Wise_Provider Wise_Patient Wise_ICD Codes.xlsx",
    ],
    "ssc": [
        "Chronic Management Patient Details - 20260403_04-55.csv",
        "Patient Diagnosis Code - 20260403_05-19.csv",
        "Patient_Medication - 20260403_06-03.csv",
    ],
    "cam": ["data_new.xlsx"],
    "cim": ["Final_Hbox_3_19_26.xlsx"],
    "xhi": [
        "EMR_Final_Report_final_part.csv",
        "medication_report.csv",
        "problem_report.csv",
    ],
}

JOB_TTL_SECONDS = 3600
SUBPROCESS_TIMEOUT = 1800
